global:
  resolve_timeout: 5m  # Time after an alert is resolved before it's marked as resolved in AlertManager.

route:
  group_by: ['alertname']  # Group alerts by the alert name before sending them to receivers.
  group_wait: 10s          # How long to wait before sending the first notification.
  group_interval: 5m       # How long to wait before sending a new notification for the same group of alerts.
  repeat_interval: 1h      # How often to send repeated notifications for the same alert.
  receiver: 'slack'        # The default receiver for all alerts.

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'  # Your Slack webhook URL
        channel: '#alerts'  # The Slack channel where alerts will be posted.

  - name: 'email'
    email_configs:
      - to: 'your-email@example.com'  # Recipient email address
        from: 'prometheus-alerts@example.com'  # Sender email address
        smarthost: 'smtp.example.com:587'  # SMTP server and port
        auth_username: 'your-smtp-username'  # SMTP username
        auth_password: 'your-smtp-password'  # SMTP password
        send_resolved: true  # Whether to send notifications when an alert is resolved.

